ourGitLabGroup = "https://gitlab.com/UniGrammar/"
ourProjectLink = ourGitLabGroup + "UniGrammar.py"
grammarsRepoLink = ourGitLabGroup + "grammars"
runtimeModuleName = "UniGrammarRuntime"
runtimeParserBackendModuleName = "IParsingBackend"
runtimeWrapperInterfaceModuleName = runtimeWrapperInterfaceName = "IWrapper"
runtimeParserResultBaseName = "IParseResult"
mainParserVarName = "__MAIN_PARSER__"
mainProductionName = "__MAIN_PRODUCTION__"
